bind 127.0.0.1
protected-mode yes
port 6379
timeout 0
tcp-keepalive 300
databases 16
dir e:/w/wx_project/jizhang/tools/redis/data
dbfilename dump.rdb
appendonly no
loglevel notice
logfile e:/w/wx_project/jizhang/tools/redis/redis.log
